### ISSUE TITLE
Cape editors

### ISSUE THREAD

**Issue by Madis0** [CaelTheColher/Capes#10]
I noticed this line in the latest changelog (haven't tested yet):

> Added a button to open OptiFine's cape editor

So how about adding those buttons to all cape providers, including vanilla (minecraft.net profile)? 

One way to do this would be displaying them side by side, e.g.

```
Optifine: ON              Cape Editor
MinecraftCapes: OFF       Cape Editor 
LabyMod: OFF              Cape Editor
...
```

**Comment by CaelTheColher** [comment]
I only added OptiFine's cape editor because that is the only way to access it
