### ISSUE TITLE
Please update to Minecraft version 1.20 for your mod.

### ISSUE THREAD

**Issue by surfishs** [CaelTheColher/Capes#100]
Please update to Minecraft version 1.20 for your mod.

**Comment by CaelTheColher** [comment]
Patience is a virtue

**Comment by surfishs** [comment]
> 耐心是一种美德

Thanks for the reply, I just wanted to make sure you were still maintaining the updates as I saw the last one on modrinth about three months ago. I'm really sorry to have disturbed you.
