### ISSUE TITLE
Config Menu crashes on click

### ISSUE THREAD

**Issue by Snapperito** [CaelTheColher/Capes#11]
heres a link to the full error - https://hastebin.com/tolihaxage.yaml

**Comment by CaelTheColher** [comment]
It seems my mod is incompatible with 1.16.1, I have update the files to reflect that. Have you considered updating to a newer Minecraft version?

**Comment by CaelTheColher** [comment]
I will upload an 1.16.1 exclusive file on CurseForge to fix this

**Comment by Snapperito** [comment]
thank you!
