### ISSUE TITLE
Capes render improperly...

### ISSUE THREAD

**Issue by realnetherbastion** [CaelTheColher/Capes#112]
No matter which cape mod you choose, all you have to do is turn it on and maybe walk around a bit and it all starts to render improperly. Such as, if you go in F5 mode, you can see the cape is there but, it's kinda' just floating off your body, and at some points when you're standing still or moving, it starts to bob on and off your body. Also, if you crouch , then the cape will always float off your body.

![2023-09-01_08 47 25](https://github.com/CaelTheColher/Capes/assets/143839052/7eb1ff4b-30ea-4690-a886-3300f11bc676)

**Comment by CaelTheColher** [comment]
Unless you are using an ancient version of this mod, it shouldn't affect cape rendering at all outside of changing the texture. So its probably caused by another mod.
