### ISSUE TITLE
Button texture cannot be changed with resource packs

### ISSUE THREAD

**Issue by Hibiii** [CaelTheColher/Capes#12]
The texture for the shortcut button in the skin customization screen can't be changed with a resource pack, even on cold boot, despite RP texture the exact same identifier to the one in the release jar.

![button texture](https://user-images.githubusercontent.com/69405847/99343105-fc091f00-286b-11eb-87e2-0474c56b1ceb.png)

**Comment by CaelTheColher** [comment]
can you send the relevant logs?

**Comment by CaelTheColher** [comment]
I tried it myself and it worked just fine. Can you also send me the resource pack you are using so I can verify?

**Comment by Hibiii** [comment]
Oddly, it started working fine, just randomly. I've done nothing except replace Canvas with Sodium but that's irrelevant, isn't it? I couldn't replicate it reloading the resource pack through the menu and in-game with F3+T. Perhaps this issue should be closed as invalid?

**Comment by CaelTheColher** [comment]
Tested with Canvas and it still worked
