### ISSUE TITLE
Authenticated profile mismatch (Optifine Cape Editor)

### ISSUE THREAD

**Issue by aqtoo** [CaelTheColher/Capes#127]
**Describe the bug**
Unable to open the Optifine cape editor

**To Reproduce**
1. Attempt to open the optifine cape editor via the Capes Mod
**Expected behavior**
A webpage to open showing the optifine cape editor.

**Screenshots**
![image](https://github.com/CaelTheColher/Capes/assets/76844190/e05786a6-d498-4221-8b22-f322ae3d1c94)

**Context (please complete the following information):**
 - Minecraft version: [e.g. 1.20.2]
 - Capes version: [1.5.3+1.20.2]

**Additional context**
When attempting to edit my cape via OptiFine_1.20.1_HD_U_I6, the cape editor opens fine with zero issues, it only happens with the cape mod.

**Comment by NEDOSTUPN0** [comment]
I have encountered the same problem and found a solution. When you click on the cape editor button, you are redirected to a link that contains your UUID, nickname, and other information. However, in Optifine, clicking on the editor button redirects you to a link with a 'Trimmed UUID' (without the '-' sign), while in the mod, you are redirected to a link with the 'full UUID' (with the '-' signs). This issue can be easily fixed. I hope this information is helpful.
