### ISSUE TITLE
Crash when starting up minecraft

### ISSUE THREAD

**Issue by ShadowTigerCool** [CaelTheColher/Capes#145]
**Describe the bug**

**To Reproduce**
1. Start the game

**Expected behavior**
For it to load correctly

**Screenshots**

**Context (please complete the following information):**
 - Minecraft version: 1.21.1
 - Fabric Loader: 0.16.6
 - Capes version: 1.5.4
 - Mod List: https://pastebin.com/iBtKywt2

**Additional context**

**Comment by CaelTheColher** [comment]
send the crash log

**Comment by ShadowTigerCool** [comment]
actually this should be fixed in fabric loader 0.16.7, seems like 0.16.6 was missing ClassLoader.registerAsParallelCapable with MixinExtras
