### ISSUE TITLE
Incompatibility with FancyMenu

### ISSUE THREAD

**Issue by seriousfreezing** [CaelTheColher/Capes#150]
I'm trying to edit the Capes interface, and every now and then the vanilla Capes buttons reappear, causing me to break the buttons I added via FancyMenu. Even though the Capes buttons are mimicked, it becomes another id.

**Context (please complete the following information):**
 - Minecraft version: 1.21.1
 - Capes version: 1.5.4
 - Mod list: https://modrinth.com/modpack/bedrock-reloaded/version/18.0.0

![image](https://github.com/user-attachments/assets/0423af59-e947-4d65-b7b5-74fde5452ffa)
[latest.log](https://github.com/user-attachments/files/17484654/latest.log)

**Comment by CaelTheColher** [comment]
Report it to FancyMenu

**Comment by seriousfreezing** [comment]
Actually, Keksuccino the developer of the FancyMenu mod, said that he can't fix it on his end. So the fix involves your side
