### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by kaxon-dev** [CaelTheColher/Capes#18]
Crash log:
[https://pastebin.com/ViHfef4H](https://pastebin.com/ViHfef4H)
Mods used:
![Wv5Ka7V](https://user-images.githubusercontent.com/19924741/118235176-a34cc480-b451-11eb-9c71-6906001c1071.png)

**Comment by CaelTheColher** [comment]
the pastebin is private

**Comment by kaxon-dev** [comment]
> the pastebin is private

Sorry for delay. I think the pastebin was awaiting manual review for some reason. Original link appears to work now in incognito mode.

**Comment by Aerodin** [comment]
I am also getting crashes that I have isolated to the Capes mod.  It seems to be worse when there are a lot of players in the area.  If there are too many players sometimes it crashes instantly.  Disabling capes I have zero issues in those situations.

**Comment by CaelTheColher** [comment]
Sorry it took a while for me to come back to this, have you tried the 1.16.5 version of the mod instead of the 1.16.1 one?
