### ISSUE TITLE
Game crashes when opening cape settings in mod menu.

### ISSUE THREAD

**Issue by Mendalton** [CaelTheColher/Capes#19]
HI, so I've just been using the new Minecraft version 1.17 and i may have experienced an issue where when I open the cape settings(on this mod) on mod menu, it ends up crashing my game for some reason. 

Opening mod settings on mod menu on other mods that i am using works just fine.

Here is the link to the crash report: https://gist.github.com/Mendalton/9028c15df7febfd6f8a63b5cf41b11a8

Any solutions?

**Comment by CaelTheColher** [comment]
I haven't really updated the mod to 1.17 yet, but I will work on it soon™

**Comment by Mendalton** [comment]
Ok, good to know!

**Comment by CaelTheColher** [comment]
Mod fully updated to 1.17 and this should be fully fixed

**Comment by CaelTheColher** [comment]
(the update is being processed by CurseForge, should be publicly available shortly)
