### ISSUE TITLE
HD capes make the elytra disappear

### ISSUE THREAD

**Issue by bluefireoly** [CaelTheColher/Capes#23]
When using an HD cape (e.g. LabyMod), the Eyltra won't be displayed, as well as the cape itself, meaning that you will just have nothing on your back - this is not the case with non-HD OptiFine capes for example.

If it is not possible to easily display the HD cape on the elytra, I think it is the best to just show the default Elytra and don't try to show anything related to the HD capes as long as the player is wearing the Elytra.

![image](https://user-images.githubusercontent.com/52456572/123683928-1a48eb80-d84d-11eb-971e-67eb6d613d3a.png)

![image](https://user-images.githubusercontent.com/52456572/123683959-2765da80-d84d-11eb-95c3-80be04a36be3.png)

**Comment by CaelTheColher** [comment]
The problem seems to be LabyMod not including an Elytra texture, so the mod is just rendering an invisible Elytra. I will try to fix it tonight.
