### ISSUE TITLE
Problem with seeing capes

### ISSUE THREAD

**Issue by andreasdc** [CaelTheColher/Capes#24]
Sometimes you have to switch from type Minecraft to Optifine to see capes, then you can go back and see again. 1.17.

**Comment by CaelTheColher** [comment]
For clarification, does this affect seeing capes from other players or just your own?

**Comment by andreasdc** [comment]
Probably both

**Comment by andreasdc** [comment]
It's hard to tell, right now I don't see my cape, when I switch to Optifine it shows, when I go back to Minecraft it's still shown.

**Comment by CaelTheColher** [comment]
> 
> 
> It's hard to tell, right now I don't see my cape, when I switch to Optifine it shows, when I go back to Minecraft it's still shown.

You mean the optifine cape or the minecraft cape?

**Comment by andreasdc** [comment]
> > It's hard to tell, right now I don't see my cape, when I switch to Optifine it shows, when I go back to Minecraft it's still shown.
> 
> So is the problem that your Minecraft cape only shows when you switch to Type OptiFine? or that your OptiFine cape is still shown when you go back to Type Minecraft?

type

**Comment by andreasdc** [comment]
After that I can switch back to Minecraft.

**Comment by CaelTheColher** [comment]
Could you take a screenshot/video (whichever is more convenient) showing the problem? I'm having a smooth-brain moment

**Comment by andreasdc** [comment]
When I have Cape type Minecraft sometimes I can't see capes. I have to switch to Optifine type to see it. After that I can switch to Minecraft type till next bug.
