### ISSUE TITLE
Vanilla Capes not shown

### ISSUE THREAD

**Issue by AmyMialee** [CaelTheColher/Capes#25]
Newer versions of the mod don't render vanilla capes at all.

**Comment by CaelTheColher** [comment]
Since I don't have a vanilla cape myself, can you help me test the fix? Join the [Cafeteria discord](https://discord.com/invite/G4PjhEf) or add me directly if its more convenient: 「 Lily 」#5284

**Comment by AmyMialee** [comment]
I myself don't have a cape, I just know people who do. You can test it with Carpet Mod fake players as they retain their copes however.
