### ISSUE TITLE
Capes not rendering on self-hosted multiplayer server

### ISSUE THREAD

**Issue by Galetaer** [CaelTheColher/Capes#27]
I've had an issue with your mod where the capes refuse to render for myself or my friends on my server, at first I thought it may be an issue with using ZeroTier, so I port forwarded the server and to my surprise the mod still doesn't render the capes. I can enter singleplayer, and it works like a charm, so it's quite an odd issue.

To clarify my settings/parameters:
- Capes are set to show in Minecraft video settings
- Capes are set to show in my character appearance settings
- All capes are set to show in the settings of your mod
- The server is port forwarded and not on a closed LAN network, though the mod did not work over simulated LAN either
- Firewall settings on my PC are set to allow Minecraft's standard port (25565) with TCP and UDP
- I check both my MinecraftCapes and Optifine capes, switching between all cape types, and neither show in multiplayer
- It works flawlessly in single player game instances
- While it hopefully goes without saying, to attempt to cover all of my bases, I do have the latest version of Fabric Capes (1.2.1)

I also already did a full reinstall of both Minecraft and your mod, but it didn't resolve the issue, so I am not sure it's likely it was a faulty installation or some 'data-based weirdness', lol

I'm no expert, but I wonder if it may be a firewall issue of some sort? Or some sort of issue with polling the cape data over the internet? The thing is, I have no idea if it would be on my end, or an odd interpretation by the mod (in this circumstance).

And I must say, as an aside, that I adore your mod! Thank you for your continued work on it, I appreciate that you are a fellow person of culture and aesthetics. ;)

**Comment by CaelTheColher** [comment]
Does it happen on dedicated third party servers like Hypixel, or is it only on local hosted servers?

**Comment by Galetaer** [comment]
It didn't happen on Hypixel (the mod functioned perfectly there), I tried another server as well (MC Complex's Vanilla Server) and my cape didn't show up until I switched the cape's display settings a bit, just cycling through which cape I'd prefer to be visible is what fixed it. I noticed it showed back up when I switched back to my Optifine cape specifically, like a user mentioned at the end of another previous issue thread (thread #24)

For my local server, however, I attempted to cycle through the cape preference setting (yet again) and it doesn't make a difference sadly; all of the capes still remain invisible for whatever reason

**Comment by CaelTheColher** [comment]
Just for a sanity check, is your server set to online-mode=true?

**Comment by Galetaer** [comment]
Yep, it's set to online-mode=true , I just double checked and confirmed it. I've had friends of mine log in from over the internet as well, as early as yesterday, so at the very least I know the server is allowing players to connect as intended
