### ISSUE TITLE
[Feature Request] Elytra Trinket support

### ISSUE THREAD

**Issue by elhertz** [CaelTheColher/Capes#29]
[Elytra Trinket](https://www.curseforge.com/minecraft/mc-mods/elytra-trinket-fabric) is a mod that uses the [Trinket API](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric) to add an extra slot for elytras
When putting an elytra on the chestplate slot this happens https://i.imgur.com/mCCQn7S.png
When putting an elytra on the elytra slot this happens https://i.imgur.com/mtxleQN.png

is it possible to fix from your side? Thanks.

**Comment by elhertz** [comment]
I'll make an issue on elytra trinket's side too.

**Comment by CaelTheColher** [comment]
Are you using the latest version? This shouldn't really happen on the latest version unless its an issue with the other mod

**Comment by CaelTheColher** [comment]
If you are using the latest (1.2.1 for Minecraft 1.17.1) version, what other mods are you using?

**Comment by elhertz** [comment]
I'm pretty sure it's an issue with Trinkets. 
And yes I forgot to add that I'm using the latest version for 1.17.1

**Comment by CaelTheColher** [comment]
Since it doesn't seem to be an issue with Capes, I will be closing this.

**Comment by CaelTheColher** [comment]
Quick Update:
It seems this problem was already fixed on the [Forge side of Caelus](
https://github.com/TheIllusiveC4/Caelus/issues/5) (funny name btw) but they forgot to fix it on Fabric.
