### ISSUE TITLE
Minecraft Cape not showing up

### ISSUE THREAD

**Issue by master-agency** [CaelTheColher/Capes#30]
When I try to use my migrator cape, I cannot see it. I also cannot see other people's migrator capes. I have an optifine cape, and that works fine, and I can see other people's optifine capes.

**Comment by CaelTheColher** [comment]
are you on the latest version for 1.17?

**Comment by master-agency** [comment]
I updated it and it fixed my issue, however the issue has come back in a different form. I can see other peoples migrator capes, but I cannot see my own. On launch if I have minecraft capes selected, nothing will show, and if I switch to my optifine cape that will show up no matter what option I have selected. If I deactivate my optifine cape, it does not show my migrator cape.

**Comment by master-agency** [comment]
When I remove the mod, the cape still does not show up, this seems to be a compatibility issue with another mod of mine.

**Comment by master-agency** [comment]
It seems to be that the migrator cape was turned off for some reason and I was too stupid to troubleshoot that.
