### ISSUE TITLE
OptiFine overwrites cape rendering

### ISSUE THREAD

**Issue by h3oCharles** [CaelTheColher/Capes#31]
**Describe the bug**

so I have optifine and optifabric installed (yes, I know, go ahead and roast me), and when cycling through capes I still have the optifine cape on

**To Reproduce**
1. have optifine, optifabric, and fabric capes installed
2. go to singleplayer, open lan
3. cycle through cape options

**Expected behavior**

capes would've cycled correctly

**Screenshots**

![2021-09-17_10 45 54](https://user-images.githubusercontent.com/8020330/133753405-78d8822f-6cda-44fe-bc85-3351bb83ef74.png)

**Context (please complete the following information):**
 - Minecraft version: 1.17.1
 - Capes version: 1.2.1
 - Mod list: optifabric-1.11.18, OptiFine_1.17.1_HD_U_G9_pre31_MOD
 - Server: singleplayer

**Additional context**

it's worth mentioning that I have a MinecraftCapes cape, an OptiFine cape, a Wynntils cape, and a vanilla migrator cape

**Comment by h3oCharles** [comment]
updated optifabric and optifine, problem still exists

optifabric-1.11.20
OptiFine_1.17.1_HD_U_G9_MOD

**Comment by h3oCharles** [comment]
found a temporary workaround of deactivating the optifine cape, problem still applies

**Comment by CaelTheColher** [comment]
The main point of this mod is to be able to use Optifine capes without installing Optifine, so its not really my priority to fix incompatibilities with it. I recommend using [Sodium and other Optifine alternatives](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) instead.
