### ISSUE TITLE
Vanilla cape appears at an unexpectedly long delay when cycling through cape options

### ISSUE THREAD

**Issue by h3oCharles** [CaelTheColher/Capes#32]
**Describe the bug**

vanilla cape either appears when choosing labymod, or appears as optifine after a long delay, either way it's the way the vanilla cape is unpredictable. is it possible to cache the vanilla capes in any way?

**To Reproduce**
1. have the mod installed
2. go to singleplayer, open lan
3. cycle through capes

**Expected behavior**

vanilla cape would appear instantly, just like mod capes do

**Screenshots**

video cuz I can't visualize this with an image
https://streamable.com/3e93d9

mod list
![image](https://user-images.githubusercontent.com/8020330/133758809-33c536c5-ee1d-4df2-84da-d5d966fdeab1.png)

**Context (please complete the following information):**
 - Minecraft version: 1.17.1
 - Capes version: 1.2.1
 - Mod list: uuh screenshot
 - Server: singleplayer, opened to lan

**Additional context**

it's worth mentioning that I have a MinecraftCapes cape, an OptiFine cape (temporarily deactivated), a Wynntils cape, and a vanilla migrator cape
I do NOT have a LabyMod cape

same problem applies when not having optifabric+optifine

**Comment by CaelTheColher** [comment]
The cape type toggle is currently very bad and I'm planning on rewriting it on the near future.
