### ISSUE TITLE
Animated MinecraftCapes Capes are appearing as a tilesheet

### ISSUE THREAD

**Issue by h3oCharles** [CaelTheColher/Capes#37]
**Describe the bug**

**To Reproduce**
I uuh buy access to animated capes on minecraftcapes, upload an animated cape, and uuh you get what I have on the screenshot

**Expected behavior**

an animated cape (duh?)

**Screenshots**

![2021-11-04_18 30 48](https://user-images.githubusercontent.com/8020330/140389837-a1ec53ce-92f6-427e-bfb1-b3b381301764.png)

![hu tao ghost](https://user-images.githubusercontent.com/8020330/140390194-70809bf0-2028-4a37-90fb-b59e9ec0a8c9.gif)

**Context (please complete the following information):**
 - Minecraft version: 1.17.1
 - Capes version: 1.2.1
 - Mod list: screenshot below
 - Server: Singleplayer

![image](https://user-images.githubusercontent.com/8020330/140390112-9b3ed483-8e8d-4220-9fd0-5c4d62d975cb.png)

**Additional context**

**Comment by CaelTheColher** [comment]
Ooops, I might have never implemented animated capes. I will work on it later™

**Comment by james090500** [comment]
Just in case it helps, the general rule of thumb is... 1 frame every 100 milliseconds. 

And you can split the cape up with....

`
            Int2ObjectMap<NativeImage> animatedCape = new Int2ObjectOpenHashMap<>();
            int totalFrames = capeImage.getHeight() / (capeImage.getWidth() / 2);
            for(int currentFrame = 0; currentFrame < totalFrames; currentFrame++) {
                NativeImage frame = new NativeImage(capeImage.getWidth(), capeImage.getWidth() / 2, true);
                for (int x = 0; x < frame.getWidth(); x++) {
                    for (int y = 0; y < frame.getHeight(); y++) {
                        frame.setPixelRGBA(x, y, capeImage.getPixelRGBA(x, y + (currentFrame * (capeImage.getWidth() / 2))));
                    }
                }
                animatedCape.put(currentFrame, frame);
            }
`
