### ISSUE TITLE
[Feature request] Optifine cosmetics request

### ISSUE THREAD

**Issue by GeekCornerGH** [CaelTheColher/Capes#38]
Optifine sometimes have cosmetics (eg: Christmas hat), and I would like to see them on this mod, is this possible ? Thanks in advance for your answer

**Comment by CaelTheColher** [comment]
I never heard about optifine having any cosmetics besides capes, can you give more context on that?

**Comment by GeekCornerGH** [comment]
Basically there is a service called [Cloaks+](https://cloaks.plus) that uses Optifine playermodels/cosmetics to show custom 3d models to the players. This system is also used by Optifine themselves to put Christmas Hats to players.

Api endpoint are: To get players cosmetics: http://s.optifine.net/html/users/IGN.cfg
Actual cosmetics files: http://s.optifine.net/html/items/COSMETIC TYPE FROM CFG FILE/{model.cfg (for model specifications) OR texture.png(assets)}

**Comment by CaelTheColher** [comment]
Cloaks+ is a third party service not affiliated with optifine, and the way it works is kinda weird so I don't think I will support it for now.

**Comment by GeekCornerGH** [comment]
I don't ask support for Cloaks+ but for Optifine playersmodels (eg santa hat)
