### ISSUE TITLE
Crash on 1.18

### ISSUE THREAD

**Issue by NatoBoram** [CaelTheColher/Capes#39]
The mod specifies `"minecraft": "1.17.x"` instead of `"minecraft": ">=1.17"`, so it crashes in Minecraft 1.18.

https://github.com/CaelTheColher/Capes/blob/master/src/main/resources/fabric.mod.json#L40

Specifying >=Current allows the mod to *potentially* function if later versions of Minecraft without any changes if a version happen to not break the mod.

At the moment, it's not possible for normal users to test if this version is compatible with 1.18.

**Comment by CaelTheColher** [comment]
The version happened to break the mod, this is why its specified what version the mod is _guaranteed_ to work in.
