### ISSUE TITLE
Jittery Cape Animations when Changing Directions

### ISSUE THREAD

**Issue by aicheye** [CaelTheColher/Capes#44]
**Describe the bug**
When changing directions with a cape equipped, the animation appears rough and jittery.

**To Reproduce**
1. Open Minecraft using the Fabric Capes mod
2. Equip a cape
3. Join a world
4. Move around and move your mouse

**Expected behavior**
In Optifine, the cape animation appears smooth.

**Context (please complete the following information):**
 - Minecraft version: 1.18,1
 - Capes version: 1.2.2
 - Mod list: Capes 1.2.2, Fabric API 0.45.0, Fabric Language Kotlin 1.7.1 Kotlin 1.6.10, Mod Menu 3.0.1
 - Server: singleplayer superflat (this issue appears in servers as well)

**Additional context**
- I am using a 144hz refresh rate monitor

https://user-images.githubusercontent.com/55955758/149440260-fb9c5efc-c2b2-4b18-86ab-770bb7ce6690.mp4
https://user-images.githubusercontent.com/55955758/149440776-8d95a1df-5b21-411d-9664-2137a0bb6aa7.mp4

**Comment by CaelTheColher** [comment]
This is a vanilla minecraft bug and its currently not in my priority list
