### ISSUE TITLE
Capes causes texture or chat bugs

### ISSUE THREAD

**Issue by assasin541** [CaelTheColher/Capes#5]
Screenshots from the bugs:
https://share.getcloudapp.com/JrugDZAL
https://share.getcloudapp.com/6quPr198
https://share.getcloudapp.com/4guJ9oGe
Mods:
https://share.getcloudapp.com/v1uxYB89

I removed Fabric Capes from the mods and there are no bugs so far.

**Comment by CaelTheColher** [comment]
Can you send the relevant log files?

**Comment by assasin541** [comment]
@CaelTheColher can I do this on discord?

**Comment by CaelTheColher** [comment]
feel free to do it

**Comment by assasin541** [comment]
@CaelTheColher how can I do that?
