### ISSUE TITLE
MinecraftCapes cape not loading/appearing.

### ISSUE THREAD

**Issue by BurnElmo** [CaelTheColher/Capes#58]
When I toggle MinecraftCapes on, the cape does not appear, I have restarted the game, however that didn't work.

**To Reproduce**
1. Go to 'Cape options'.
2. Click on 'Cape Type' until MinecraftCapes appears.
4. Cape does not load.

**Expected behavior**
MinecraftCapes cape to appear.

**Context (please complete the following information):**
 - Minecraft version: [e.g. 1.19]
 - Capes version: [e.g. 1.4.4]
 - Mod list: Just fps boosting mods (sodium, phosphor, lithium etc.)
 - Server: Singleplayer

**Comment by CaelTheColher** [comment]
Can you run the command `/capes debug` and send the result here?

**Comment by BurnElmo** [comment]
I realized that when I click the cape type until it goes to MinecraftCapes, the toggle doesn't enable it and disable the previous cape, so I was able to change it manually in the toggle menu.

**Comment by BurnElmo** [comment]
I realized that when I click the cape type until it goes to MinecraftCapes, the toggle doesn't enable it and disable the previous cape, so I was able to change it manually in the toggle menu.
