### ISSUE TITLE
Minecraft cape overwrites other capes

### ISSUE THREAD

**Issue by Suntix06** [CaelTheColher/Capes#61]
**Describe the bug**
I'm trying to update my cape to my Minecraft Capes cape but it didn't update ingame. I disabled the cape on the Skin and relaunched Minecraft which didn't work either.  It also wont update to my Optifine cape.

**To Reproduce**
1. Go to 'Options'
2. Go to 'Skin Customization'
3. Click on the Fabric Capes button
4. Go to 'Cape Selector'
6. See error

**Expected behavior**
The cape updates to the selected cape

**Screenshots**
![2022-08-18_19 37 34](https://user-images.githubusercontent.com/111528555/185460089-761a2c59-4282-4c0a-8c60-bb875b636929.png)
![2022-08-18_19 43 16](https://user-images.githubusercontent.com/111528555/185460260-66ceea3c-d0fd-44b3-9bbc-c0db9103d9c9.png)

**Debug info**
Name: Suntix_
UUID: a20e62ef-9020-4eb7-9541-0ef577a59b3b
Type: MINECRAFTCAPES
IsAnimated: false
HasElytraTexture: true
URL: https://minecraftcapes.net/profile/a20e62ef90204eb795410ef577a59b3b

**Context (please complete the following information):**
 - Minecraft version: 1.19
 - Capes version: 1.4.3
 - Mod list: 3D Skin Layers, Appleskin, Bookshelf, Capes, Entity-Culling, Essential, Detailed Armor Bar, Iris Shaders, Lazy DFU, Lithium, Reeses Sodium Options, Sodium, Simple Voicechat, Wavey Capes, Xaeros Minimap
 - Server: Singleplayer, multiple public servers

**Comment by CaelTheColher** [comment]
This is a known issue with Essential
![image](https://user-images.githubusercontent.com/16297430/185549092-e24ebdea-8312-4a68-9744-26b016781602.png)
