### ISSUE TITLE
my cape not showing in multiplayer

### ISSUE THREAD

**Issue by GodGun968** [CaelTheColher/Capes#63]
**Describe the bug**
My cape and elytra skin are showing in single player
But when I join the server my cape doesn't show up, other players are normal

**To Reproduce**
1.join server
2.F5

**Expected behavior**
Showing my cape and elytra skin in multiplayer game
**Screenshots**

**Debug info**
multiplayer game:
Name: GodGun968
UUID: 1edb1ade-1ed0-3ed8-99c7-98161b7a1fd7
Type: null
IsAnimated: false
HasElytraTexture: true
URL: null
single player game:
Name: GodGun968
UUID: 6d9ee49c-22d4-4185-ba3a-4d0339583bbd
Type: MINECRAFTCAPES
IsAnimated: false
HasElytraTexture: true
URL: https://minecraftcapes.net/profile/6d9ee49c22d44185ba3a4d0339583bbd

**Context (please complete the following information):**
 - Minecraft version: [1.19.2]
 - Capes version: [1.4.4+1.19]
 - Mod list: [Using the Fabulously Optimized mod pack]
 - Server: [Private]

**Additional context**
The server is a server that non-genuine can also join
The server uses paper and skin display plugins
I use Fabulously Optimized mod pack default setting
cape type :MinecraftCapes
Toggle :enable all

**Comment by CaelTheColher** [comment]
This is a problem with how offline mode servers work, sadly I can't do a lot about it

**Comment by GodGun968** [comment]
> This is a problem with how offline mode servers work, sadly I can't do a lot about it

okay, but can you merge Chinese translation
https://github.com/CaelTheColher/Capes/pull/60
