### ISSUE TITLE
Huge slutters/hangs on servers like Hypixel when Lithium is present.

### ISSUE THREAD

**Issue by HyperSoop** [CaelTheColher/Capes#64]
**Describe the bug**
With certain cape providers toggled on, Hypixel freezes the game a few seconds after world join (reports were 10-20 seconds - for me it's a complete hang, equivalent to a crash)

**To Reproduce**
1. Go to capes settings and enable one or all of the affected cape providers
2. Join Hypixel and wait a few seconds while chunks load
3. Get a huge hang/slutter

**Expected behavior**
No lag.

**Context (please complete the following information):**
 - Minecraft version: 1.19.2
 - Capes version: 1.4.5
 - Mod list: General optimization mods - the issue was isolated to with Capes.
 - Server: Hypixel

**Additional context**
The problem was discussed in the Fabulously Optimized discord server for a while on a support thread. I could relate this to the early issue in Vanilla, where requests to the Mojang servers to check whether a player is ignored in chat blocked the render thread and caused severe lag spikes - you could dig in this direction for the fix.
The affected cape providers (slow response times?) were Cosmetica, LabyMod, Wynntils, Cloaks+

After some time it was determined that it was caused by pairing Capes with Lithium.

**Comment by HyperSoop** [comment]
As it turns out it actually is some mod causing it as an incopatibility. Will try to isolate the one too.

**Comment by HyperSoop** [comment]
It was Lithium. What a crossover.

**Comment by HyperSoop** [comment]
The bug, as it turns out, also causes a slutter upon opening the config menu (loading the player preview?)

**Comment by CaelTheColher** [comment]
Seems to still happen in 1.5, guess its time to fully investigate it

**Comment by CaelTheColher** [comment]
This time I actually tested it properly and it should be fixed.

And thanks to @HeyZeer0 for instantly identifying the problem and how to fix it.
