### ISSUE TITLE
"Other" button in settings doesn't change when selected

### ISSUE THREAD

**Issue by Oondanomala** [CaelTheColher/Capes#66]
**Describe the bug**
In the settings the "other" button doesn't become blank when selected like the others

**To Reproduce**
1. Open the capes settings menu
2. Click on "Other"
3. Notice it not changing :(

**Expected behavior**
It should change like the other buttons

**Screenshots**

https://user-images.githubusercontent.com/87101222/192821776-88b67e52-f016-4db8-8faa-95ed8a10a2f9.mp4

**Context:**
 - Minecraft version: 1.19.2
 - Capes version: 1.4.5
 - Mod list: Only this mod (and required deps)

**Comment by CaelTheColher** [comment]
fixed in 1.5
