### ISSUE TITLE
Settings Crash with (probably) Wildfire's Female Gender Mod

### ISSUE THREAD

**Issue by GhostIsBeHere** [CaelTheColher/Capes#68]
**Describe the bug**
Game crashes when clicking the settings button in Mod Menu. Not Enough Crashes identified Capes and Wildfire's Female Gender Mod as the causes.

**To Reproduce**
1. Make new instance with Fabric 1.19.2, Capes, WFGM, Mod Menu, and Not Enough Crashes
2. Launch Game
3. Open Mod Menu
4. Click "Settings" button for Capes
5. Crash to NEC crash reporter

**Expected behavior**
Open the settings window

**Screenshots**

**Debug info**
Cannot run `/capes debug` in the main menu

**Context (please complete the following information):**
 - Minecraft version: 1.19.2
 - Capes version: 1.4.5
 - Mod list: 
[https://paste.gg/p/anonymous/2d8c5df387cc4477931359f45942e30d](https://paste.gg/p/anonymous/2d8c5df387cc4477931359f45942e30d)
 - Server: Main Menu (Not in a world or server)

**Additional Info**
Crash report: [https://bytebin.lucko.me/I7oiDxZ5DV](https://bytebin.lucko.me/I7oiDxZ5DV)
Crash report on Crashy: [https://crashy.net/BggSiHCW6eiuIRgLjVek](https://crashy.net/BggSiHCW6eiuIRgLjVek)

**Comment by CaelTheColher** [comment]
My scuffed fakeplayer render attacks again.

Workaround for now should be to only open the menu while in a world, but I will look to rewrite the render in a way that wont conflict with mods assuming vanilla behavior.
