### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by andreasdc** [CaelTheColher/Capes#70]
**Describe the bug**
Crash when joining server

**To Reproduce**
When you join the server and connection is cancelled, you get crashed.

**Expected behavior**
No crashes
**Screenshots**

**Debug info**
The result from the command `/capes debug`

**Context (please complete the following information):**
 - Minecraft version: 1.19.2
 - Capes version: latest curseforge
 - Mod list: -
 - Server: multiplayer

**Additional context**
if you need anything more im here

**Comment by CaelTheColher** [comment]
Can you send the relevant crash report?

**Comment by andreasdc** [comment]
It doesn't generate crash report, just hs_err file.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9b0f2c42a, pid=9536, tid=13384
#
# JRE version: Java(TM) SE Runtime Environment (18.0.1.1+2) (build 18.0.1.1+2-6)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (18.0.1.1+2-6, mixed mode, sharing, tiered, compressed class ptrs, z gc, windows-amd64)
# Problematic frame:
# C  0x00007ff9b0f2c42a
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows

**Comment by andreasdc** [comment]
I don't know how did that happen but I think it's not the capes fault.
