### ISSUE TITLE
crash on menu when clicking on the cape icon

### ISSUE THREAD

**Issue by h3oCharles** [CaelTheColher/Capes#72]
**Describe the bug**

**To Reproduce**

after initializing Minecraft, go to Options, Skin Customization, and click on the Capes icon

**Expected behavior**

the menu would load

**Screenshots**

N/A?

**Debug info**
The result from the command `/capes debug`

is this still needed even if i didn't load a world yet?

**Context (please complete the following information):**
 - Minecraft version: 1.19.2
 - Capes version: Capes-1.4.5+1.19.jar
 - Mod list: screenshot below
 - Server: N/A?

![image](https://user-images.githubusercontent.com/8020330/201479479-afd9b223-4c7d-4e38-9b7f-699eb60d812b.png)

**Additional context**

here's a crash report from Crashy https://crashy.net/RPFfoUgE72wmxWnsiFAg

EDIT: still crashed after loading a world, here's /capes debug

Name: h3oCharles
UUID: 2c3f5fc7-30c1-4821-ae5c-2e3f07868b1a
Type: null
IsAnimated: false
HasElytraTexture: true
URL: null

it's worth mentioning that at the time of writing, i only have a Migrator cape, and a disabled OptiFine cape

EDIT2: Seems like Distant Horizons are a problem, disabling that mod and reproducing fixed this problem, i still wanna see your thoughts, however

**Comment by CaelTheColher** [comment]
Known issue, I'm currently looking for a fix
