### ISSUE TITLE
MCCI Utils Mod Game Loading Loop on Start because MCCI Utils introduced custom capes

### ISSUE THREAD

**Issue by kispintyi** [CaelTheColher/Capes#73]
**Describe the bug**
In the latest update MCCI Utils Developer added custom cape support so now if I want to use this mod and the MCCI Utils Mod at the same time, the two will have an issue with loading the game (infinite loading loop like it is reloading the resourcepacks again, again and again, forever, you can see it in the video I attached) which shouldn't have happened because I use other mods that include capes, but the Cape mod _does_ work with them but not with this mod (MCCI Utils).

**To Reproduce**
1. Go to 'https://modrinth.com/mod/mcci-utils'
2. Click on 'Changelog'
3. Download 'the latest (0.14) Version with custom capes'
4. Start the game 'with the Cape mod and the MCCI Utils mod you just downloaded'
5. The game 'loading will loop but not crash (Like it is reloading the resourcepacks, forever)'

**Expected behavior**

The game should load simply fine and should not give me a loading loop.

**Screenshots**
![kép_2022-12-01_201312326](https://user-images.githubusercontent.com/116653691/205139596-48e38b6e-2ebb-4a4a-924c-f9e06d2425d3.png)

**Media**

https://user-images.githubusercontent.com/116653691/205131150-05ede08f-d0bb-456e-9ba0-a09e2abb2f77.mp4

**Debug info**
The result from the command `/capes debug`: I can't even type it because my game doesn't even load, it's just looping but I attached the latest.log, the least I can get
My latest.log: [latest.log](https://github.com/CaelTheColher/Capes/files/10135170/latest.log)

**Context**
 - Minecraft version: 1.19.2
 - Capes version: 1.4.5
 - Mod list: Starlight, Entityculling, Iris Shaders, Mod Menu, Client Tweaks, WorldEdit, AntiGhost, Capes, Cloth Config v8, Clumps-forge, Cull Particles, Debugify, Dynamic FPS, Enhanced Block Entities, EntityCulling-Fabric, Essential-fabric, Exordium, Fabric Language Kotlin, FerriteCore, Indium, Island Champ, Island Menu, IslandUtils, Krypton, LambDynamicLights, Lithium, MCCI Utils, MCCI: Companion, MoreCosmetics, Not Enough Crashes, Noxesium, Particle Culling, Phosphor, Reese's Sodium Options, Replay Mod, Skin Layers 3D, Smooth Boot, Sodium, Sodium Extra, YetAnotherConfigLib, item-model-fix
 - Server: Not server related

**Additional context**
We with the MCCI Utils Developer had a conversation about this in Feather and they figured out too that it's not related to them nor the MCCI Utils Developer.
The Feather Ticket Transcript: https://transcripts.feathermc.com/direct?url=https://cdn.discordapp.com/attachments/1047218143342379049/1047936246988669088/1047220705084846130.html or here, just need to unzip it: 
[1047220705084846130.zip](https://github.com/CaelTheColher/Capes/files/10135439/1047220705084846130.zip)

The MCCI Utils mod's Developer's working on a fix! If... he can solve this from his perspective that is.

**Comment by CaelTheColher** [comment]
We are both redirecting at the same place and Mixins doesn't like that, should be an easy fix. I will do it from my side when 1.19.3 gets released, if MCCI doesn't release a fix first.

**Comment by kispintyi** [comment]
Great to hear! Thanks! 😅 😊 👍

**Comment by kispintyi** [comment]
Update: MCCI Utils mod's Developer is away from home for 3 months and working a full-time job too so I don't think he can release an update! @CaelTheColher

**Comment by CaelTheColher** [comment]
seems to be fixed from mcci utils's side
