### ISSUE TITLE
Game crash when I click on the menu icon.

### ISSUE THREAD

**Issue by twompchop** [CaelTheColher/Capes#76]
**Describe the bug**
My OptiFine cape wasn't showing up, so I went to the menu and my game crashed

**To Reproduce**
1. Go to Options
2. Click on Skin Customization
3. Click on the Capes icon

**Expected behavior**
I expected a menu to come up with what capes I'd like to see

**Screenshots**
Button: 
![image](https://user-images.githubusercontent.com/120344259/206935536-9bf58e10-5b2c-414f-9cce-e7473f881a9f.png)

Crash:
![image](https://user-images.githubusercontent.com/120344259/206935500-f03b944e-199b-4d36-ace5-5220c5d869c5.png)

**Debug info**
Name: dtwomp
UUID: e5b23ebb-a9b5-4cea-94b4-6ed2988f806b
Type: null
IsAnimated: false
HasElytraTexture: true
URL: null

**Context (please complete the following information):**
 - Minecraft version: 1.19.3
 - Capes version: 1.4.5
 - Mod list: Sodium, Mod Menu, Iris, Dynamic FPS, & Capes. (Fabric API & Kotlin too)
 - Server: Singleplayer

**Additional context**
Clicking the menu in Mod Menu doesn't work either

**Comment by CaelTheColher** [comment]
Capes has been updated to 1.19.3 yet but I'm working on it
