### ISSUE TITLE
Multiple mod conflicts related to the cape preview in the options

### ISSUE THREAD

**Issue by CaelTheColher** [CaelTheColher/Capes#77]
While version 1.5 should fix most of these issues, there might be old or new conflicts that I'm not sure still remain.

All new issues related to this will be documented here.

**Comment by CaelTheColher** [comment]
#64 still happens and seems to be unrelated to this issue.

**Comment by JakeKanive** [comment]
As of 2/27/2023 this is still an issue, clicking the Capes button in Skin Customization results in a CTD because of multiple mod incompatibilities including Wavy Capes, Customizable Elytra, and Wildfire's Female Gender Mod to name a few

**Comment by CaelTheColher** [comment]
> As of 2/27/2023 this is still an issue, clicking the Capes button in Skin Customization results in a CTD because of multiple mod incompatibilities including Wavy Capes, Customizable Elytra, and Wildfire's Female Gender Mod to name a few

what version are you using?

**Comment by CaelTheColher** [comment]
I just did a quick test with Wavey Capes and Customizable Elytra using the latest Capes version (1.5.2 for Minecraft 1.19.3) and there were no crashes so far

**Comment by zohfur** [comment]
Capes version 1.4.5 (latest for 1.19.2) crashes with Wavey Capes v1.3.2 (latest for 1.19.2) for me as well.

**Comment by CaelTheColher** [comment]
> Capes version 1.4.5 (latest for 1.19.2) crashes with Wavey Capes v1.3.2 (latest for 1.19.2) for me as well.

its definitely broken on that version since I only fixed it on version 1.5

**Comment by zohfur** [comment]
Would you be able to backport the fix to 1.19.2? Most mods have not updated yet and compatibility for 1.19.3 is rough.

**Comment by CaelTheColher** [comment]
> Would you be able to backport the fix to 1.19.2? Most mods have not updated yet and compatibility for 1.19.3 is rough.

done
