### ISSUE TITLE
Wynntils Capes Not Working

### ISSUE THREAD

**Issue by KsGamer82** [CaelTheColher/Capes#81]
**Describe the bug**
Simply put, capes aren't showing on my client using Wynntils and the Fabric Capes mod.

**To Reproduce**
1. Install Wynntils Artemis (for MC 1.19.3)
2. Install Fabric Capes mod and other required mods (Fabric up to date)
3. Log into Wynncraft
4. Capes for Wynntils won't appear on own character.

**Expected behavior**
I was expecting to see my Wynntils assigned cape after installing this mod.

**Screenshots**
![2023-01-05_23 10 03](https://user-images.githubusercontent.com/60792137/210934926-e21164c2-5638-4c52-b708-fa3860513c30.png)

**Debug info**
The result from the command `/capes debug`
Name: MightyMagi82
UUID: 1d9e0088-6069-4c50-8e65-20e29d9d80ed
Type: null
IsAnimated: false
HasElytraTexture: true
URL: null

**Context (please complete the following information):**
 - Minecraft version: 1.19.3
 - Capes version: 1.5.1
 - Mod list: Fabric API, Fabric Language Kotlin, Wynntils
 - Server: play.wynncraft.com (multiplayer)

**Comment by CaelTheColher** [comment]
Check if your cape type is set to Wynntils and Wynntils is enabled on the "Toggle" menu in the mod options

**Comment by KsGamer82** [comment]
I'm afraid I do not know how to get to mod options on Wynntils or Wynncraft, waiting for an answer from Wynntils discord server atm.

**Comment by CaelTheColher** [comment]
> I'm afraid I do not know how to get to mod options on Wynntils or Wynncraft, waiting for an answer from Wynntils discord server atm.
I meant on the mod options for Capes...

**Comment by KsGamer82** [comment]
How do I get to it on capes?

**Comment by KsGamer82** [comment]
I finally found where to go to to toggle options for capes. Thanks for leading me the right way!
