### ISSUE TITLE
Capes menu crashes game when clicked

### ISSUE THREAD

**Issue by Denzy2** [CaelTheColher/Capes#84]
**Describe the bug**
The game crashes once you click on the Capes menu on 1.16.5 version

**To Reproduce**
1. Launch game on 1.16.5 version with Capes
2. Click on the options menu 
4. Click on skin customization menu 
5. Click on the Capes icon to open Capes menu 
6. Crash, See error

**Expected behavior**
Expected for the Capes menu to open once I clicked the icon in skin customization menu.

**Context (please complete the following information):**
 - Minecraft version: [e.g. 1.16.5]
 - Capes version: [e.g. 1.1.2]

**Additional context**
The game crash code is: 
" The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler "

**Comment by CaelTheColher** [comment]
Sorry I don't support versions this old, but if you share the full log I might help identify what other mod is causing the issue

**Comment by Denzy2** [comment]
![image](https://user-images.githubusercontent.com/76097025/212700855-fa72acb2-ab37-4b3c-b7c2-3c8ec005f740.png)
these are all the mods in my mods folder 
[crash-2023-01-16_16.24.58-client.txt](https://github.com/CaelTheColher/Capes/files/10426630/crash-2023-01-16_16.24.58-client.txt)
and this is the crash report

**Comment by Denzy2** [comment]
> Sorry I don't support versions this old, but if you share the full log I might help identify what other mod is causing the issue
![image](https://user-images.githubusercontent.com/76097025/212701411-db44c9b8-2dfc-47a0-832f-cf5bad6e16c1.png)
these are all the mods in my mods folder
[crash-2023-01-16_16.24.58-client.txt](https://github.com/CaelTheColher/Capes/files/10426640/crash-2023-01-16_16.24.58-client.txt)
and this is the latest crash report

**Comment by CaelTheColher** [comment]
You might have downloaded the 1.16.1 version instead of the 1.16.5 version but I can't be sure. Other than that I can't really help with a version this old, sorry.
