### ISSUE TITLE
CONFIG BUTTON ON MOD MENU DOES NOT WORK

### ISSUE THREAD

**Issue by yaboimello** [CaelTheColher/Capes#94]
**Describe the bug**
When i press the config button on mod menu it cloes my minecraft

**To Reproduce**
go to mod menu 
press the config 
game closes for me

**Expected behavior**
i thought i would be able to use it and config it 

 - Minecraft version: 1.19.2
 - Capes version: didnt have a cape on just downloaded it
 - Mod list: sodium
 - Server: was not in a server i pressed config

**Additional context**
please help

**Comment by CaelTheColher** [comment]
send crash report

**Comment by TRemill** [comment]
Faced with the same problem, then crash log https://crashy.net/3c060c2c-42bb-4999-aa30-900c5e2ac67b
[crash-2023-05-16_03.56.53-client.txt](https://github.com/CaelTheColher/Capes/files/11482505/crash-2023-05-16_03.56.53-client.txt)
